### ISSUE TITLE
v1.5 Config Changes

### ISSUE THREAD

**Issue by ghost** [mozilla-services/pushgo#180]
This ticket tracks config changes in v1.5.0.
- [x] Removed `[router].pool_size` (#167).
- [x] Added `[default].always_route` (#170).
- [x] Moved `[discovery]` retry configs to the `[discovery.retry]` section (#145).
- [x] Added `[balancer]` and `[balancer.retry]` sections (#144).
- [x] Added `[propping].idle_conns` and `[router].idle_conns` (#153).
- [x] Added `[handlers]` and `[handlers.max_data_len]` (#135).
- [x] Converted `[router]` into an extensible section; added `[router].max_data_len` (#154).
- [x] Moved `[default].origins` to `[handlers].origins` (#168).
